title: Tiffany Tso
email: thetiffanytso@gmail.com
description: Portfolio and personal website of software developer Tiffany Tso. Includes her resume, her past projects, and her social media links. Happy browsing! 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tiffanytso.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: thetiffanytso
github_username:  tiffanytso

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
